# Generated by Django 3.0.3 on 2020-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=120)),
                ('business_name', models.CharField(max_length=250)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('street_address', models.CharField(max_length=250)),
                ('street_address_2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='United States', max_length=20)),
                ('business_type', models.CharField(max_length=20)),
                ('store_type', models.CharField(choices=[('deli', 'Deli'), ('cafe', 'Cafe'), ('electronics', 'Electronics'), ('ice cream parlour', 'Ice cream parlour'), ('restaurant', 'Restaurant'), ('other', 'Other')], default='deli', max_length=100)),
                ('registration_date', models.DateField()),
            ],
        ),
    ]
