# Generated by Django 3.0.3 on 2020-02-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=2, max_length=90),
            preserve_default=False,
        ),
    ]
