# Generated by Django 3.0.3 on 2020-02-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200227_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(default='this is so cool'),
        ),
    ]
