# Generated by Django 3.0.3 on 2020-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='store_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
